name: gblan
services:
  gblan-util:
    image: ubuntu:22.04
    container_name: gblan-util
    hostname: gblan-util
    tty: true
    command: sleep infinity
    working_dir: /share
    volumes:
      - share-data:/share
      - sshd-etc-ssh-data:/sshd-etc-ssh-data
      - sshd-home-data:/sshd-home-data

volumes:
  share-data:
    name: gblan-share-data
    external: true
  sshd-etc-ssh-data:
    name: gblan-sshd-etc-ssh-data
    external: true
  sshd-home-data:
    name: gblan-sshd-home-data
    external: true
