name: gblan
services:
  gblan-share:
    image: ubuntu:22.04
    container_name: gblan-share
    hostname: gblan-share
    tty: true
    command: sleep infinity
    working_dir: /share
    volumes:
      - share-data:/share
    network_mode: "none"

volumes:
  share-data:
    name: gblan-share-data
