name: gblan-dev-mkcert
services:
  gblan-dev-mkcert:
    image: gblan-dev-mkcert:1.0
    container_name: gblan-dev-mkcert
    hostname: gblan-dev-mkcert
    tty: true
    command: sleep infinity
    working_dir: /root
    volumes:
      - mkcert-root-data:/root
      - mkcert-keys-data:/mkcert-keys
      - share-data:/share
    network_mode: "none"

volumes:
  mkcert-root-data:
    name: gblan-dev-mkcert-root
  mkcert-keys-data:
    name: gblan-dev-mkcert-keys-data
  share-data:
    name: gblan-dev-share-data
